fix: adding types for options
gicornachini/bolsa pull request #4
Opened 2021-03-14 02:42 UTC by lclpedro

2021-03-16 12:50 UTC, gicornachini requested changes
Muito bom ter mais pessoas para contribuir, eu não tenho opções portanto não conseguiria adicionar esta informação sozinho! thanks 😄

2021-03-16 12:50 UTC, gicornachini commented on bolsa/constants.py
> +    'Exercicio de Opções': BrokerAssetExtractMarketType.UNIT.value
Curiosidade, o "Exercicio" não tem acento mesmo? Obs: não opero opções
```python
    'Exercicio de Opções': BrokerAssetExtractMarketType.UNIT.value
```

2021-03-16 12:50 UTC, gicornachini commented on bolsa/constants.py
> +    'Mercado a Vista': BrokerAssetExtractMarketType.UNIT.value,
O que acha de adicionar teste para estes novos valores?

https://github.com/gicornachini/bolsa/blob/master/bolsa/test/test_constans.py

2021-03-16 12:50 UTC, gicornachini commented on CHANGELOG.md
> +2.0.3 (2021-01-07)
Desculpe por não ter um `CONTRIBUTING`, ainda 🤦 .

Essa parte do `Changelog.md`, `.bumpversion.cfg` e `setup.py`, pode remover, pq geramos estas alterações quando fecharmos uma nova release.

2021-03-16 12:51 UTC, gicornachini commented
@lclpedro se puder adicionar uma descrição no PR tbm para ficar documentado 🙏

2021-03-16 13:21 UTC, pedrolucasl commented on bolsa/constants.py
> +    'Exercicio de Opções': BrokerAssetExtractMarketType.UNIT.value
Exatamente isso hehehe.. eu acabei pegando do próprio resultado retornado por eles na hora que eu executei qui!

2021-03-16 13:22 UTC, pedrolucasl commented on bolsa/constants.py
> +    'Mercado a Vista': BrokerAssetExtractMarketType.UNIT.value,
É uma boa, vou providenciar isso!

2021-03-27 16:22 UTC, oDjonathanKrause approved these changes

2021-03-27 21:33 UTC, gicornachini commented
Alteração feita em outro PR https://github.com/gicornachini/bolsa/pull/5 .

2021-03-27 21:33 UTC, closed without merging